spring.application.name=tads_aulas

# Datasource Configuration
# localhost
spring.datasource.url=jdbc:mariadb://localhost:3306/tads_aulas?createDatabaseIfNotExist=true
spring.datasource.username=root
# MARIADB_SECRET Ã© uma variÃ¡vel de ambiente (ou utiliza o valor depois dos dois pontos)
spring.datasource.password=${MARIADB_SECRET:mariadb}

# JPA
# Hibernate ddl auto (create, create-drop, update, none): com "update" o esquema do database Ã© automaticamente
# modificado, conforme as anotaÃ§Ãµes JPA nas entidades Java da camada de modelo.
spring.jpa.hibernate.ddl-auto=update
# JPA-SQL (as propriedades abaixo instruem o Spring Boot a imprimir o SQL e formatÃ¡-lo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# adia a inicialização da execução dos scripts para depois da criação dos EntityManager do JPA (o padrão é o script executar antes do JPA)
spring.jpa.defer-datasource-initialization=false
# ordena a execução dos scripts do arquivo data.sql (Valor na primeira execução always. Lembre de colocar para never depois da primeira execução)
spring.sql.init.mode=never

# spring-data-rest
spring.data.rest.basePath=/api

# Secret para geração do token JWT
# As chaves indicam ao Spring Boot para ele procurar por uma variável de ambiente a partir do valor que está nela.
# Após os : é o valor que ele utiliza caso não localize a variável de ambiente. No caso, procura por JWT_SECRET, senão, aplica 12345678
api.security.token.secret=${JWT_SECRET:12345678}
